services:
  trip_planner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/symfony
    networks:
      - trip_planner_nt

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/symfony:ro
    ports:
      - "${NGINX_PORT:-8080}:80" # grab it from the .env file
    depends_on:
      - trip_planner
    networks:
      - trip_planner_nt

  tpmysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tripplannerdb}
      MYSQL_USER: ${MYSQL_USER:-tripplannerus}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Gizmo123}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trip_planner_nt

networks:
  trip_planner_nt:

volumes:
  mysql_data:
